[2023-12-28T09:09:24.804+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2023-12-27T00:00:00+00:00 [queued]>
[2023-12-28T09:09:24.809+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a scheduled__2023-12-27T00:00:00+00:00 [queued]>
[2023-12-28T09:09:24.809+0000] {taskinstance.py:2171} INFO - Starting attempt 26 of 28
[2023-12-28T09:09:24.816+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): table_source_a> on 2023-12-27 00:00:00+00:00
[2023-12-28T09:09:24.824+0000] {standard_task_runner.py:60} INFO - Started process 1024 to run task
[2023-12-28T09:09:24.828+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_datalake', 'table_source_a', 'scheduled__2023-12-27T00:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_datalake.py', '--cfg-path', '/tmp/tmp0cdqv5vj']
[2023-12-28T09:09:24.829+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask table_source_a
[2023-12-28T09:09:24.877+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_datalake.table_source_a scheduled__2023-12-27T00:00:00+00:00 [running]> on host 64bb4a2d8189
[2023-12-28T09:09:24.988+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_datalake' AIRFLOW_CTX_TASK_ID='table_source_a' AIRFLOW_CTX_EXECUTION_DATE='2023-12-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='26' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-27T00:00:00+00:00'
[2023-12-28T09:09:25.032+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-28T09:09:25.038+0000] {logging_mixin.py:188} INFO - ----DEBUG service_account_scope: https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/drive,https://www.googleapis.com/auth/spreadsheets
[2023-12-28T09:09:28.421+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-28T09:09:28.504+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_datalake, task_id=table_source_a, execution_date=20231227T000000, start_date=20231228T090924, end_date=20231228T090928
[2023-12-28T09:09:28.578+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-28T09:09:28.623+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
